src/app/performance/forms.py
from flask_wtf import Form
from flask_wtf.file import FileField, FileAllowed, FileRequired
from wtforms import SubmitField


class UploadForm(Form):
    transactions = FileField('Upload a CSV file of your transactions', validators=[FileRequired('Please chose a file!'), FileAllowed(['csv', 'CSV'], 'CSV only!')])
    submit = SubmitField('Upload')

src/app/performance/__init__.py
from flask import Blueprint

performance = Blueprint('performance', __name__)

from . import routes

src/app/performance/routes.py
import os, csv, time
from flask import render_template, current_app, request, redirect, url_for, flash, json, jsonify, make_response, Response
from . import performance
from .forms import UploadForm
from werkzeug import secure_filename
from flask_wtf.file import FileField

import pandas as pd

from flask.ext.login import login_required, current_user, session
from ..models import User
from ..pf_utils import pf_utils as utils
from ..pf_utils import pf_utils as pf
from pandas.tseries import offsets
from pandas import datetime
from pandas import Series
from pandas.tseries.offsets import Week, BDay
from datetime import date

from app import cache
from app import db

@performance.route('/get_performance', methods=['GET', 'POST'])
@login_required
def get_performance():
    if request.method == "POST":
        print(str(request.form))
        keys = list(request.form.keys())
        print(keys)
        keys.remove('src')
        print(keys)
        
        idx = [];
        for key in keys:
            idx.append(request.form[key])
        
        print(idx)
        
     
        tr_by_date_df=pd.read_sql_table('transaction_'+str(current_user.get_id()), db.engine, index_col='date')
        symbols=pf.get_symbols(tr_by_date_df)

# try getting rates from sql and check that they are up to date
        try:
            cumrates=pd.read_sql_table('cumrates'+str(current_user.get_id()), db.engine, index_col='date')
            cumrates = Series(cumrates['0'], index=cumrates.index)
            
            today = datetime.now().replace(hour=0, minute=0, second=0, microsecond=0)
            last_b_day = pd.date_range(start=today-Week(), end=today, freq=BDay())[-1]-BDay(1)
            last_day = cumrates.index[-1].to_datetime()
            
            print(today)
            print(last_day)
            print(last_b_day)

            if (last_day != last_b_day):
                [worth, cumrates, invalid]=  pf.get_rates_df(pf.get_holdings(tr_by_date_df, symbols), symbols, tr_by_date_df)
                cumrates.to_sql('cumrates'+str(current_user.get_id()), db.engine, if_exists='replace')
                worth.to_sql('worth'+str(current_user.get_id()), db.engine, if_exists='replace')
    
        except:
            [worth, cumrates, invalid]=  pf.get_rates_df(pf.get_holdings(tr_by_date_df, symbols), symbols, tr_by_date_df)
            cumrates.to_sql('cumrates'+str(current_user.get_id()), db.engine, if_exists='replace')
            worth.to_sql('worth'+str(current_user.get_id()), db.engine, if_exists='replace')
        


        [idx_rates, invalid] = pf.get_index_rates(pf.get_cashflow(tr_by_date_df), idx)
        if len(invalid)>0:
            err = "Invalid simbols: "+str(invalid)
        else:
            err = ""

        if (request.form['src'] == 'max'):
            print('requesting max')
            return jsonify(post_data(cumrates, idx_rates))
        
        elif (request.form['src'] == 'ytd'):
            print('requesting ytd')
            #get last business day of last year
            last_day_of_last_year = pd.date_range('12/1/'+str(date.today().year-1), periods=1, freq='BM')
            
            #get cumrates from begining of the year and divide by last day of previous year
            ytd_cumrates = cumrates[str(date.today().year)+'-1-1':date.today()]/cumrates[last_day_of_last_year[0]]
            
            #repeat for index
            ytd_idx = idx_rates
            for i in idx:
                ytd_idx[i] = idx_rates[i][str(date.today().year)+'-1-1':date.today()]/idx_rates[i][last_day_of_last_year[0]]

            return jsonify(post_data(ytd_cumrates, ytd_idx))

        
        elif (request.form['src'] == '1month'):
            print('requesting 1month')
            delta = BDay(20)
            last = BDay(21)
        
            month_cumrates = cumrates[cumrates.index[-1]-delta:cumrates.index[-1]]/cumrates[cumrates.index[-1]-last]
        
            month_idx = idx_rates
            for i in idx:
                month_idx[i] = idx_rates[i][idx_rates[i].index[-1]-delta:idx_rates[i].index[-1]]/idx_rates[i][idx_rates[i].index[-1]-last]
        
            return jsonify(post_data(month_cumrates, month_idx))

        elif (request.form['src'] == '1year'):
            print('requesting 1year')
            
            delta = BDay(250)
            last = BDay(251)
            
            year_cumrates = cumrates[cumrates.index[-1]-delta:cumrates.index[-1]]/cumrates[cumrates.index[-1]-last]
            
            year_idx = idx_rates
            
            for i in idx:
                year_idx[i] = idx_rates[i][idx_rates[i].index[-1]-delta:idx_rates[i].index[-1]]/idx_rates[i][idx_rates[i].index[-1]-last]
           
            return jsonify(post_data(year_cumrates, year_idx))

    return Response("ok")

def post_data(cumrates, idx_rates):
    # turn index to strings, remove time
    dates_l=list(str(x) for x in cumrates.index)
    for i in range(0, len(dates_l)):
        dates_l[i]=dates_l[i].split(' ')[0]
   
    #create lists for highcharts
    pf_rates=list((cumrates.values-1)*100)

    json_data = {}
    json_data["axis"]=dates_l
    json_data["data"]=pf_rates
    for key in idx_rates.keys():
        json_data[key]=list((idx_rates[key].values-1)*100)

    return json_data


@performance.route('/performance')
@login_required
def performance():
    
    return render_template('performance/performance.html')

src/app/templates/performance/performance.html
{% extends "base.html" %}

{% block head %}
{{ super() }}
{% endblock %}

{% block styles %}
{{super()}}

<link rel="stylesheet" type="text/css" href="//cdn.datatables.net/1.10.5/css/jquery.dataTables.css">
<link rel="stylesheet" href="http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js">

{% endblock %}

{% block page_content %}
    
    <!--<div class="container">
        <div id={{ chartID|safe }}></div>

    </div>
    <div class="container">
        
        <div id={{ chartID1|safe }}></div>

    </div>-->
    
    <ul class="nav nav-tabs">
        <li role="presentation" class="active"><a href="#">Return</a></li>
        <li role="presentation"><a href="#">Value</a></li>
    </ul>
    
    <div class="container">
        
        <div id="container" style="height: 400px; min-width: 310px"></div>
        
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-left">

                    <button type="submit" name="button" class="btn btn-default navbar-btn" onclick="zoom_data('ytd')">YTD</button>
                    <button type="submit" name="button" class="btn btn-default navbar-btn" onclick="zoom_data('1year')">1 Year</button>
                    <button type="submit" name="button" class="btn btn-default navbar-btn" onclick="zoom_data('1month')">1 Month</button>
                    <button type="submit" name="button" class="btn btn-default navbar-btn" onclick="zoom_data('max')">Max</button>
         
                </div>
                <div class="navbar-form navbar-right">
                    <div class="form-group">
                        <input type="text" class="form-control" id="compare" placeholder="Ticker">
                    </div>
                    <button class="btn btn-default" onclick="compare()">Compare</button>
                    <button class="btn btn-default" onclick="reset()">Reset</button>
                </div>
            </div>
        </nav>
        
    </div>
    
    
{% endblock %}

{% block scripts %}
{{ super() }}
    <script type="text/javascript" charset="utf8" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-2.1.1.min.js"></script>

    <script src="http://cdn.datatables.net/1.10.5/js/jquery.dataTables.min.js"></script>
    <script src="http://cdn.datatables.net/plug-ins/f2c75b7247b/integration/bootstrap/3/dataTables.bootstrap.js"></script>
    

    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="http://code.highcharts.com/highcharts-3d.js"></script>
    <script src="http://code.highcharts.com/modules/funnel.js"></script>
    
    <!--<script src="http://code.highcharts.com/stock/highstock.js"></script>-->
    <script src="http://code.highcharts.com/stock/modules/exporting.js"></script>
    
    <!--<script src="../static/graph.js"></script>-->


    <script>
        function compare() {
            compare_tickers.push(document.getElementById('compare').value)
            get_chart_data(current_view, options, compare_tickers)
        }
    
    function reset() {
        compare_tickers = []
        get_chart_data(current_view, options, compare_tickers)

    }
    </script>

    <script>
        var compare_tickers = []
        var current_view = 'max'
                          var options = {
                            chart: {
                                renderTo: 'container',
                                zoomType: 'x'
                            },
                            title: {
                                text: 'Time-Weighted Return'
                            },
                            subtitle: {
                                text: document.ontouchstart === undefined ?
                                'Click and drag in the plot area to zoom in' :
                                'Pinch the chart to zoom in'
                            },
                            xAxis: {},
                            yAxis: {"title": {"text": '% Return '}},
                            legend: {
                          
                                layout: 'vertical',
                                align: 'left',
                                verticalAlign: 'top',
                                borderWidth: 0,
                                x: 110,
                                y: 50,
                                floating: true
                            },
                          
                            plotOptions: {
                                area: {
                                    fillColor: {
                                        linearGradient: { x1: 0, y1: 0, x2: 0, y2: 1},
                                        stops: [
                                                [0, Highcharts.getOptions().colors[0]],
                                                [1, Highcharts.Color(Highcharts.getOptions().colors[0]).setOpacity(0).get('rgba')]
                                                ]
                                    },
                                    marker: {
                                        radius: 2
                                    },
                                    lineWidth: 1,
                                    states: {
                                        hover: {
                                            lineWidth: 1
                                        }
                                    },
                                    threshold: null
                                }
                            },
                          
                            series: [{}]
                          };
        
        
        $(document).ready(function() {
                          
                          get_chart_data("max", options, compare_tickers)
        
                          
        })
                          
                          
        function get_chart_data(source, options, compare){
          
           
            idx_data = {}
            for(var i = 0; i < compare.length; i++) {
                idx_data[String(i)] = compare[i]
            }
            
            
            $.post( "{{ url_for('performance.get_performance') }}", {"src" : source, "idx" : idx_data}, function (data) {
                                        
                                        //console.log(data)
                   
                                        chart_series = []
                   chart_series.push({name:'portfolio', data:data.data})
                   
                                        for(var i = 0; i < compare.length; i++) {
                                            tmp = {}
                                            tmp['name'] = compare[i]
                                            tmp['data'] = data[compare[i]]
                                            chart_series.push(tmp)
                   
                                        }
                   
                                        options.xAxis = {"categories": data.axis};
                                        /*options.series =  [{
                                                           name: 'portfolio',
                                                           data: data.data
                                                           },
                                                           {
                                                           name: 'spy',
                                                           data: data.spy
                                                           },
                                                           {
                                                           name: 'iwm',
                                                           data: data.iwm
                                                           }]*/
                                        options.series = chart_series
                                        var chart = new Highcharts.Chart(options);
                                        
                                        //$('#container').highcharts(options);
                                        }, "json")
                                        //.success(function() { alert("success"); })
                                        .error(function() { alert("An error occured during the request"); })
                                        //.complete(function() { alert("complete"); });
                          }
    
    function zoom_data (source) {
        current_view = source;
        get_chart_data(source, options, compare_tickers)
        
    }
    
    </script>





{% endblock %}